// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_16u_config2_s_HH_
#define _compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_16u_config2_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0.h"
#include "shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s.h"

namespace ap_rtl {

struct compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_16u_config2_s : public sc_module {
    // Port declarations 72
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > p_read;
    sc_out< sc_lv<16> > res_stream_V_data_0_V_din;
    sc_in< sc_logic > res_stream_V_data_0_V_full_n;
    sc_out< sc_logic > res_stream_V_data_0_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_1_V_din;
    sc_in< sc_logic > res_stream_V_data_1_V_full_n;
    sc_out< sc_logic > res_stream_V_data_1_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_2_V_din;
    sc_in< sc_logic > res_stream_V_data_2_V_full_n;
    sc_out< sc_logic > res_stream_V_data_2_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_3_V_din;
    sc_in< sc_logic > res_stream_V_data_3_V_full_n;
    sc_out< sc_logic > res_stream_V_data_3_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_4_V_din;
    sc_in< sc_logic > res_stream_V_data_4_V_full_n;
    sc_out< sc_logic > res_stream_V_data_4_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_5_V_din;
    sc_in< sc_logic > res_stream_V_data_5_V_full_n;
    sc_out< sc_logic > res_stream_V_data_5_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_6_V_din;
    sc_in< sc_logic > res_stream_V_data_6_V_full_n;
    sc_out< sc_logic > res_stream_V_data_6_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_7_V_din;
    sc_in< sc_logic > res_stream_V_data_7_V_full_n;
    sc_out< sc_logic > res_stream_V_data_7_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_8_V_din;
    sc_in< sc_logic > res_stream_V_data_8_V_full_n;
    sc_out< sc_logic > res_stream_V_data_8_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_9_V_din;
    sc_in< sc_logic > res_stream_V_data_9_V_full_n;
    sc_out< sc_logic > res_stream_V_data_9_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_10_V_din;
    sc_in< sc_logic > res_stream_V_data_10_V_full_n;
    sc_out< sc_logic > res_stream_V_data_10_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_11_V_din;
    sc_in< sc_logic > res_stream_V_data_11_V_full_n;
    sc_out< sc_logic > res_stream_V_data_11_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_12_V_din;
    sc_in< sc_logic > res_stream_V_data_12_V_full_n;
    sc_out< sc_logic > res_stream_V_data_12_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_13_V_din;
    sc_in< sc_logic > res_stream_V_data_13_V_full_n;
    sc_out< sc_logic > res_stream_V_data_13_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_14_V_din;
    sc_in< sc_logic > res_stream_V_data_14_V_full_n;
    sc_out< sc_logic > res_stream_V_data_14_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_15_V_din;
    sc_in< sc_logic > res_stream_V_data_15_V_full_n;
    sc_out< sc_logic > res_stream_V_data_15_V_write;
    sc_out< sc_logic > res_stream_V_data_0_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_1_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_2_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_3_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_4_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_5_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_6_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_7_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_8_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_9_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_10_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_11_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_12_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_13_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_14_V_blk_n;
    sc_out< sc_logic > res_stream_V_data_15_V_blk_n;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_16u_config2_s(sc_module_name name);
    SC_HAS_PROCESS(compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_16u_config2_s);

    ~compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_16u_config2_s();

    sc_trace_file* mVcdFile;

    dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0* grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160;
    shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s* call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<16> > kernel_data_V_1_1;
    sc_signal< sc_lv<16> > kernel_data_V_1_2;
    sc_signal< sc_lv<16> > kernel_data_V_1_4;
    sc_signal< sc_lv<16> > kernel_data_V_1_5;
    sc_signal< sc_lv<16> > kernel_data_V_1_7;
    sc_signal< sc_lv<16> > kernel_data_V_1_8;
    sc_signal< sc_lv<32> > sX_2;
    sc_signal< sc_lv<32> > sY_2;
    sc_signal< sc_lv<32> > pY_2;
    sc_signal< sc_lv<32> > pX_2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > and_ln289_2_reg_567;
    sc_signal< sc_lv<16> > kernel_data_V_1_6_ret_reg_522;
    sc_signal< sc_lv<16> > kernel_data_V_1_3_ret_reg_527;
    sc_signal< sc_lv<16> > kernel_data_V_1_0_ret_reg_532;
    sc_signal< sc_lv<16> > kernel_data_V_1_1_ret_reg_537;
    sc_signal< sc_lv<16> > kernel_data_V_1_2_ret_reg_542;
    sc_signal< sc_lv<16> > kernel_data_V_1_4_ret_reg_547;
    sc_signal< sc_lv<16> > kernel_data_V_1_5_ret_reg_552;
    sc_signal< sc_lv<16> > kernel_data_V_1_7_ret_reg_557;
    sc_signal< sc_lv<16> > kernel_data_V_1_8_ret_reg_562;
    sc_signal< sc_lv<1> > and_ln289_2_fu_363_p2;
    sc_signal< sc_lv<1> > icmp_ln313_fu_369_p2;
    sc_signal< sc_lv<1> > icmp_ln313_reg_571;
    sc_signal< sc_lv<32> > select_ln328_fu_393_p3;
    sc_signal< sc_lv<32> > select_ln328_reg_575;
    sc_signal< sc_lv<1> > icmp_ln317_fu_413_p2;
    sc_signal< sc_lv<1> > icmp_ln317_reg_580;
    sc_signal< sc_lv<32> > select_ln323_fu_437_p3;
    sc_signal< sc_lv<32> > select_ln323_reg_584;
    sc_signal< sc_lv<16> > tmp_data_0_V_reg_589;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<16> > tmp_data_1_V_reg_594;
    sc_signal< sc_lv<16> > tmp_data_3_V_reg_599;
    sc_signal< sc_lv<16> > tmp_data_4_V_reg_604;
    sc_signal< sc_lv<16> > tmp_data_5_V_reg_609;
    sc_signal< sc_lv<16> > tmp_data_6_V_reg_614;
    sc_signal< sc_lv<16> > tmp_data_7_V_reg_619;
    sc_signal< sc_lv<16> > tmp_data_8_V_reg_624;
    sc_signal< sc_lv<16> > tmp_data_9_V_reg_629;
    sc_signal< sc_lv<16> > tmp_data_10_V_reg_634;
    sc_signal< sc_lv<16> > tmp_data_11_V_reg_639;
    sc_signal< sc_lv<16> > tmp_data_12_V_reg_644;
    sc_signal< sc_lv<16> > tmp_data_13_V_reg_649;
    sc_signal< sc_lv<16> > tmp_data_14_V_reg_654;
    sc_signal< sc_lv<16> > tmp_data_15_V_reg_659;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_start;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_done;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_idle;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_ready;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_0;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_1;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_2;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_3;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_4;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_5;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_6;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_7;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_8;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_9;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_10;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_11;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_12;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_13;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_return_14;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_ce;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_start;
    sc_signal< sc_logic > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_done;
    sc_signal< sc_logic > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_idle;
    sc_signal< sc_logic > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_ready;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_0;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_1;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_2;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_3;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_4;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_5;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_6;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_7;
    sc_signal< sc_lv<16> > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_return_8;
    sc_signal< sc_logic > call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_ce;
    sc_signal< sc_lv<32> > storemerge_reg_149;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_start_reg;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_NS_fsm_state2;
    sc_signal< sc_lv<32> > add_ln321_fu_419_p2;
    sc_signal< sc_lv<32> > add_ln326_fu_375_p2;
    sc_signal< sc_logic > io_acc_block_signal_op95;
    sc_signal< bool > ap_block_state4;
    sc_signal< sc_lv<31> > tmp_fu_315_p4;
    sc_signal< sc_lv<31> > tmp_143_fu_335_p4;
    sc_signal< sc_lv<1> > icmp_ln289_fu_295_p2;
    sc_signal< sc_lv<1> > icmp_ln289_1_fu_305_p2;
    sc_signal< sc_lv<1> > icmp_ln289_4_fu_325_p2;
    sc_signal< sc_lv<1> > icmp_ln289_5_fu_345_p2;
    sc_signal< sc_lv<1> > and_ln289_1_fu_357_p2;
    sc_signal< sc_lv<1> > and_ln289_fu_351_p2;
    sc_signal< sc_lv<32> > add_ln328_fu_387_p2;
    sc_signal< sc_lv<32> > add_ln323_fu_431_p2;
    sc_signal< bool > ap_condition_133;
    sc_signal< bool > ap_condition_742;
    sc_signal< bool > ap_condition_746;
    sc_signal< bool > ap_condition_741;
    sc_signal< bool > ap_condition_752;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_1B;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln321_fu_419_p2();
    void thread_add_ln323_fu_431_p2();
    void thread_add_ln326_fu_375_p2();
    void thread_add_ln328_fu_387_p2();
    void thread_and_ln289_1_fu_357_p2();
    void thread_and_ln289_2_fu_363_p2();
    void thread_and_ln289_fu_351_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_NS_fsm_state2();
    void thread_ap_block_state4();
    void thread_ap_condition_133();
    void thread_ap_condition_741();
    void thread_ap_condition_742();
    void thread_ap_condition_746();
    void thread_ap_condition_752();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_ce();
    void thread_call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_173_ap_start();
    void thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_ce();
    void thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_160_ap_start();
    void thread_icmp_ln289_1_fu_305_p2();
    void thread_icmp_ln289_4_fu_325_p2();
    void thread_icmp_ln289_5_fu_345_p2();
    void thread_icmp_ln289_fu_295_p2();
    void thread_icmp_ln313_fu_369_p2();
    void thread_icmp_ln317_fu_413_p2();
    void thread_io_acc_block_signal_op95();
    void thread_res_stream_V_data_0_V_blk_n();
    void thread_res_stream_V_data_0_V_din();
    void thread_res_stream_V_data_0_V_write();
    void thread_res_stream_V_data_10_V_blk_n();
    void thread_res_stream_V_data_10_V_din();
    void thread_res_stream_V_data_10_V_write();
    void thread_res_stream_V_data_11_V_blk_n();
    void thread_res_stream_V_data_11_V_din();
    void thread_res_stream_V_data_11_V_write();
    void thread_res_stream_V_data_12_V_blk_n();
    void thread_res_stream_V_data_12_V_din();
    void thread_res_stream_V_data_12_V_write();
    void thread_res_stream_V_data_13_V_blk_n();
    void thread_res_stream_V_data_13_V_din();
    void thread_res_stream_V_data_13_V_write();
    void thread_res_stream_V_data_14_V_blk_n();
    void thread_res_stream_V_data_14_V_din();
    void thread_res_stream_V_data_14_V_write();
    void thread_res_stream_V_data_15_V_blk_n();
    void thread_res_stream_V_data_15_V_din();
    void thread_res_stream_V_data_15_V_write();
    void thread_res_stream_V_data_1_V_blk_n();
    void thread_res_stream_V_data_1_V_din();
    void thread_res_stream_V_data_1_V_write();
    void thread_res_stream_V_data_2_V_blk_n();
    void thread_res_stream_V_data_2_V_din();
    void thread_res_stream_V_data_2_V_write();
    void thread_res_stream_V_data_3_V_blk_n();
    void thread_res_stream_V_data_3_V_din();
    void thread_res_stream_V_data_3_V_write();
    void thread_res_stream_V_data_4_V_blk_n();
    void thread_res_stream_V_data_4_V_din();
    void thread_res_stream_V_data_4_V_write();
    void thread_res_stream_V_data_5_V_blk_n();
    void thread_res_stream_V_data_5_V_din();
    void thread_res_stream_V_data_5_V_write();
    void thread_res_stream_V_data_6_V_blk_n();
    void thread_res_stream_V_data_6_V_din();
    void thread_res_stream_V_data_6_V_write();
    void thread_res_stream_V_data_7_V_blk_n();
    void thread_res_stream_V_data_7_V_din();
    void thread_res_stream_V_data_7_V_write();
    void thread_res_stream_V_data_8_V_blk_n();
    void thread_res_stream_V_data_8_V_din();
    void thread_res_stream_V_data_8_V_write();
    void thread_res_stream_V_data_9_V_blk_n();
    void thread_res_stream_V_data_9_V_din();
    void thread_res_stream_V_data_9_V_write();
    void thread_select_ln323_fu_437_p3();
    void thread_select_ln328_fu_393_p3();
    void thread_tmp_143_fu_335_p4();
    void thread_tmp_fu_315_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
