// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_ST_fsm_state1 = "1";
const sc_lv<2> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_ST_fsm_state2 = "10";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv32_1 = "1";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv32_7 = "111";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv32_F = "1111";
const sc_lv<2> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv2_0 = "00";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv32_8 = "1000";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv32_11 = "10001";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv32_6 = "110";
const sc_lv<18> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv18_0 = "000000000000000000";
const sc_lv<1> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv1_0 = "0";
const sc_lv<10> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv10_1 = "1";
const sc_lv<10> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv10_3FF = "1111111111";
const sc_lv<10> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv10_2 = "10";
const sc_lv<6> dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_lv6_0 = "000000";
const bool dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::ap_const_boolean_1 = true;

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_10_V_fu_699_p2);
    sensitive << ( trunc_ln_reg_969 );
    sensitive << ( add_ln703_399_fu_695_p2 );

    SC_METHOD(thread_acc_11_V_fu_704_p2);
    sensitive << ( mult_27_V_reg_958 );

    SC_METHOD(thread_acc_14_V_fu_714_p2);
    sensitive << ( add_ln703_402_reg_1049 );
    sensitive << ( add_ln703_403_fu_709_p2 );

    SC_METHOD(thread_acc_15_V_fu_725_p2);
    sensitive << ( add_ln703_405_reg_1054 );
    sensitive << ( add_ln703_406_fu_719_p2 );

    SC_METHOD(thread_acc_1_V_fu_637_p2);
    sensitive << ( mult_33_V_reg_964 );
    sensitive << ( add_ln703_382_fu_632_p2 );

    SC_METHOD(thread_acc_3_V_fu_647_p2);
    sensitive << ( mult_19_V_reg_953 );
    sensitive << ( add_ln703_384_fu_642_p2 );

    SC_METHOD(thread_acc_4_V_fu_657_p2);
    sensitive << ( add_ln703_386_reg_1029 );
    sensitive << ( add_ln703_387_fu_652_p2 );

    SC_METHOD(thread_acc_5_V_fu_666_p2);
    sensitive << ( add_ln703_389_reg_1034 );
    sensitive << ( add_ln703_391_fu_662_p2 );

    SC_METHOD(thread_acc_7_V_fu_671_p2);
    sensitive << ( trunc_ln708_133_reg_979 );

    SC_METHOD(thread_acc_8_V_fu_680_p2);
    sensitive << ( add_ln703_394_reg_1044 );
    sensitive << ( add_ln703_395_fu_676_p2 );

    SC_METHOD(thread_acc_9_V_fu_690_p2);
    sensitive << ( trunc_ln708_136_reg_989 );
    sensitive << ( add_ln703_397_fu_685_p2 );

    SC_METHOD(thread_add_ln703_382_fu_632_p2);
    sensitive << ( trunc_ln708_132_reg_974 );
    sensitive << ( trunc_ln708_137_fu_586_p4 );

    SC_METHOD(thread_add_ln703_384_fu_642_p2);
    sensitive << ( trunc_ln708_144_reg_1018 );

    SC_METHOD(thread_add_ln703_386_fu_534_p2);
    sensitive << ( mult_52_V_fu_272_p4 );
    sensitive << ( mult_36_V_fu_230_p4 );

    SC_METHOD(thread_add_ln703_387_fu_652_p2);
    sensitive << ( trunc_ln708_141_reg_1001 );

    SC_METHOD(thread_add_ln703_389_fu_540_p2);
    sensitive << ( trunc_ln708_132_fu_352_p4 );
    sensitive << ( mult_53_V_fu_288_p4 );

    SC_METHOD(thread_add_ln703_390_fu_546_p2);
    sensitive << ( trunc_ln708_142_fu_470_p4 );

    SC_METHOD(thread_add_ln703_391_fu_662_p2);
    sensitive << ( trunc_ln708_136_reg_989 );
    sensitive << ( add_ln703_390_reg_1039 );

    SC_METHOD(thread_add_ln703_394_fu_552_p2);
    sensitive << ( mult_33_V_fu_220_p4 );
    sensitive << ( trunc_ln708_136_fu_416_p4 );

    SC_METHOD(thread_add_ln703_395_fu_676_p2);
    sensitive << ( trunc_ln708_142_reg_1006 );
    sensitive << ( trunc_ln708_145_reg_1023 );

    SC_METHOD(thread_add_ln703_397_fu_685_p2);
    sensitive << ( acc_13_V_reg_1011 );

    SC_METHOD(thread_add_ln703_399_fu_695_p2);
    sensitive << ( trunc_ln708_140_reg_995 );
    sensitive << ( trunc_ln708_145_reg_1023 );

    SC_METHOD(thread_add_ln703_402_fu_558_p2);
    sensitive << ( trunc_ln708_145_fu_524_p4 );
    sensitive << ( trunc_ln708_134_fu_378_p4 );

    SC_METHOD(thread_add_ln703_403_fu_709_p2);
    sensitive << ( mult_27_V_reg_958 );
    sensitive << ( mult_14_V_fu_580_p1 );

    SC_METHOD(thread_add_ln703_405_fu_564_p2);
    sensitive << ( sext_ln708_fu_330_p1 );
    sensitive << ( mult_15_V_fu_154_p4 );

    SC_METHOD(thread_add_ln703_406_fu_719_p2);
    sensitive << ( sext_ln708_80_fu_624_p1 );
    sensitive << ( sext_ln708_79_fu_583_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_0_V_write_assign_fu_730_p3 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_1_V_write_assign_fu_738_p3 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_11_V_write_assign_fu_820_p3 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_12_V_write_assign_fu_828_p3 );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_13_V_write_assign_fu_835_p3 );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_14_V_write_assign_fu_842_p3 );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_15_V_write_assign_fu_850_p3 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_3_V_write_assign_fu_746_p3 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_4_V_write_assign_fu_754_p3 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_5_V_write_assign_fu_762_p3 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_6_V_write_assign_fu_780_p3 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_7_V_write_assign_fu_788_p3 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_8_V_write_assign_fu_796_p3 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_9_V_write_assign_fu_804_p3 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( res_10_V_write_assign_fu_812_p3 );

    SC_METHOD(thread_mult_14_V_fu_580_p1);
    sensitive << ( trunc_ln708_s_reg_948 );

    SC_METHOD(thread_mult_15_V_fu_154_p4);
    sensitive << ( sub_ln1118_fu_148_p2 );

    SC_METHOD(thread_mult_33_V_fu_220_p4);
    sensitive << ( sub_ln1118_185_fu_214_p2 );

    SC_METHOD(thread_mult_36_V_fu_230_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_mult_36_V_fu_230_p4);
    sensitive << ( mult_36_V_fu_230_p1 );

    SC_METHOD(thread_mult_52_V_fu_272_p4);
    sensitive << ( sub_ln1118_187_fu_266_p2 );

    SC_METHOD(thread_mult_53_V_fu_288_p4);
    sensitive << ( sub_ln1118_210_fu_282_p2 );

    SC_METHOD(thread_p_Val2_s_fu_628_p2);
    sensitive << ( trunc_ln708_140_reg_995 );
    sensitive << ( acc_13_V_reg_1011 );

    SC_METHOD(thread_p_shl3_fu_402_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_p_shl3_fu_402_p3);
    sensitive << ( p_shl3_fu_402_p1 );

    SC_METHOD(thread_p_shl5_fu_338_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_p_shl5_fu_338_p3);
    sensitive << ( p_shl5_fu_338_p1 );

    SC_METHOD(thread_res_0_V_write_assign_fu_730_p3);
    sensitive << ( p_Val2_s_fu_628_p2 );

    SC_METHOD(thread_res_10_V_write_assign_fu_812_p3);
    sensitive << ( acc_10_V_fu_699_p2 );

    SC_METHOD(thread_res_11_V_write_assign_fu_820_p3);
    sensitive << ( acc_11_V_fu_704_p2 );

    SC_METHOD(thread_res_12_V_write_assign_fu_828_p3);
    sensitive << ( tmp_32_reg_1059 );

    SC_METHOD(thread_res_13_V_write_assign_fu_835_p3);
    sensitive << ( acc_13_V_reg_1011 );

    SC_METHOD(thread_res_14_V_write_assign_fu_842_p3);
    sensitive << ( acc_14_V_fu_714_p2 );

    SC_METHOD(thread_res_15_V_write_assign_fu_850_p3);
    sensitive << ( acc_15_V_fu_725_p2 );

    SC_METHOD(thread_res_1_V_write_assign_fu_738_p3);
    sensitive << ( acc_1_V_fu_637_p2 );

    SC_METHOD(thread_res_3_V_write_assign_fu_746_p3);
    sensitive << ( acc_3_V_fu_647_p2 );

    SC_METHOD(thread_res_4_V_write_assign_fu_754_p3);
    sensitive << ( acc_4_V_fu_657_p2 );

    SC_METHOD(thread_res_5_V_write_assign_fu_762_p3);
    sensitive << ( acc_5_V_fu_666_p2 );

    SC_METHOD(thread_res_6_V_write_assign_fu_780_p3);
    sensitive << ( tmp_fu_770_p4 );

    SC_METHOD(thread_res_7_V_write_assign_fu_788_p3);
    sensitive << ( acc_7_V_fu_671_p2 );

    SC_METHOD(thread_res_8_V_write_assign_fu_796_p3);
    sensitive << ( acc_8_V_fu_680_p2 );

    SC_METHOD(thread_res_9_V_write_assign_fu_804_p3);
    sensitive << ( acc_9_V_fu_690_p2 );

    SC_METHOD(thread_sext_ln1116_253_cast_fu_198_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_sext_ln1116_253_cast_fu_198_p1);
    sensitive << ( sext_ln1116_253_cast_fu_198_p0 );

    SC_METHOD(thread_sext_ln1116_254_cast_fu_254_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_sext_ln1116_254_cast_fu_254_p1);
    sensitive << ( sext_ln1116_254_cast_fu_254_p0 );

    SC_METHOD(thread_sext_ln1116_255_cast_fu_334_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_sext_ln1116_255_cast_fu_334_p1);
    sensitive << ( sext_ln1116_255_cast_fu_334_p0 );

    SC_METHOD(thread_sext_ln1116_256_cast_fu_398_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_sext_ln1116_256_cast_fu_398_p1);
    sensitive << ( sext_ln1116_256_cast_fu_398_p0 );

    SC_METHOD(thread_sext_ln1116_258_cast_fu_426_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_sext_ln1116_258_cast_fu_426_p1);
    sensitive << ( sext_ln1116_258_cast_fu_426_p0 );

    SC_METHOD(thread_sext_ln1116_259_cast_fu_480_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_sext_ln1116_259_cast_fu_480_p1);
    sensitive << ( sext_ln1116_259_cast_fu_480_p0 );

    SC_METHOD(thread_sext_ln1116_cast22_fu_126_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_sext_ln1116_cast22_fu_126_p1);
    sensitive << ( sext_ln1116_cast22_fu_126_p0 );

    SC_METHOD(thread_sext_ln1118_326_fu_604_p1);
    sensitive << ( shl_ln1118_176_fu_596_p3 );

    SC_METHOD(thread_sext_ln1118_fu_210_p1);
    sensitive << ( shl_ln1118_173_fu_202_p3 );

    SC_METHOD(thread_sext_ln708_79_fu_583_p1);
    sensitive << ( trunc_ln708_312_reg_984 );

    SC_METHOD(thread_sext_ln708_80_fu_624_p1);
    sensitive << ( trunc_ln708_313_fu_614_p4 );

    SC_METHOD(thread_sext_ln708_fu_330_p1);
    sensitive << ( trunc_ln708_311_fu_320_p4 );

    SC_METHOD(thread_shl_ln1118_173_fu_202_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_shl_ln1118_173_fu_202_p3);
    sensitive << ( shl_ln1118_173_fu_202_p1 );

    SC_METHOD(thread_shl_ln1118_174_fu_240_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_shl_ln1118_174_fu_240_p3);
    sensitive << ( shl_ln1118_174_fu_240_p1 );

    SC_METHOD(thread_shl_ln1118_175_fu_258_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_shl_ln1118_175_fu_258_p3);
    sensitive << ( shl_ln1118_175_fu_258_p1 );

    SC_METHOD(thread_shl_ln1118_176_fu_596_p3);
    sensitive << ( ap_port_reg_data_6_V_read );

    SC_METHOD(thread_shl_ln1118_177_fu_430_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_shl_ln1118_177_fu_430_p3);
    sensitive << ( shl_ln1118_177_fu_430_p1 );

    SC_METHOD(thread_shl_ln1118_178_fu_484_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_shl_ln1118_178_fu_484_p3);
    sensitive << ( shl_ln1118_178_fu_484_p1 );

    SC_METHOD(thread_shl_ln1118_s_fu_174_p3);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_shl_ln_fu_140_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_shl_ln_fu_140_p3);
    sensitive << ( shl_ln_fu_140_p1 );

    SC_METHOD(thread_sub_ln1118_184_fu_182_p2);
    sensitive << ( shl_ln1118_s_fu_174_p3 );

    SC_METHOD(thread_sub_ln1118_185_fu_214_p2);
    sensitive << ( sext_ln1118_fu_210_p1 );

    SC_METHOD(thread_sub_ln1118_186_fu_248_p2);
    sensitive << ( shl_ln1118_174_fu_240_p3 );
    sensitive << ( sext_ln1116_253_cast_fu_198_p1 );

    SC_METHOD(thread_sub_ln1118_187_fu_266_p2);
    sensitive << ( shl_ln1118_175_fu_258_p3 );
    sensitive << ( sext_ln1116_254_cast_fu_254_p1 );

    SC_METHOD(thread_sub_ln1118_188_fu_298_p2);
    sensitive << ( shl_ln1118_175_fu_258_p3 );

    SC_METHOD(thread_sub_ln1118_189_fu_304_p2);
    sensitive << ( sext_ln1116_254_cast_fu_254_p1 );
    sensitive << ( sub_ln1118_188_fu_298_p2 );

    SC_METHOD(thread_sub_ln1118_190_fu_362_p2);
    sensitive << ( sext_ln1116_255_cast_fu_334_p1 );
    sensitive << ( p_shl5_fu_338_p3 );

    SC_METHOD(thread_sub_ln1118_191_fu_608_p2);
    sensitive << ( sext_ln1118_326_fu_604_p1 );

    SC_METHOD(thread_sub_ln1118_192_fu_438_p2);
    sensitive << ( shl_ln1118_177_fu_430_p3 );
    sensitive << ( sext_ln1116_258_cast_fu_426_p1 );

    SC_METHOD(thread_sub_ln1118_193_fu_492_p2);
    sensitive << ( shl_ln1118_178_fu_484_p3 );
    sensitive << ( sext_ln1116_259_cast_fu_480_p1 );

    SC_METHOD(thread_sub_ln1118_210_fu_282_p2);
    sensitive << ( shl_ln1118_175_fu_258_p3 );
    sensitive << ( sext_ln1116_254_cast_fu_254_p1 );

    SC_METHOD(thread_sub_ln1118_211_fu_346_p2);
    sensitive << ( sext_ln1116_255_cast_fu_334_p1 );
    sensitive << ( p_shl5_fu_338_p3 );

    SC_METHOD(thread_sub_ln1118_212_fu_410_p2);
    sensitive << ( sext_ln1116_256_cast_fu_398_p1 );
    sensitive << ( p_shl3_fu_402_p3 );

    SC_METHOD(thread_sub_ln1118_213_fu_454_p2);
    sensitive << ( shl_ln1118_177_fu_430_p3 );
    sensitive << ( sext_ln1116_258_cast_fu_426_p1 );

    SC_METHOD(thread_sub_ln1118_214_fu_508_p2);
    sensitive << ( shl_ln1118_178_fu_484_p3 );
    sensitive << ( sext_ln1116_259_cast_fu_480_p1 );

    SC_METHOD(thread_sub_ln1118_fu_148_p2);
    sensitive << ( shl_ln_fu_140_p3 );
    sensitive << ( sext_ln1116_cast22_fu_126_p1 );

    SC_METHOD(thread_tmp_fu_770_p4);
    sensitive << ( sub_ln1118_191_fu_608_p2 );

    SC_METHOD(thread_trunc_ln708_132_fu_352_p4);
    sensitive << ( sub_ln1118_211_fu_346_p2 );

    SC_METHOD(thread_trunc_ln708_134_fu_378_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_trunc_ln708_134_fu_378_p4);
    sensitive << ( trunc_ln708_134_fu_378_p1 );

    SC_METHOD(thread_trunc_ln708_136_fu_416_p4);
    sensitive << ( sub_ln1118_212_fu_410_p2 );

    SC_METHOD(thread_trunc_ln708_137_fu_586_p4);
    sensitive << ( ap_port_reg_data_6_V_read );

    SC_METHOD(thread_trunc_ln708_142_fu_470_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_trunc_ln708_142_fu_470_p4);
    sensitive << ( trunc_ln708_142_fu_470_p1 );

    SC_METHOD(thread_trunc_ln708_145_fu_524_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_trunc_ln708_145_fu_524_p4);
    sensitive << ( trunc_ln708_145_fu_524_p1 );

    SC_METHOD(thread_trunc_ln708_311_fu_320_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_trunc_ln708_311_fu_320_p4);
    sensitive << ( trunc_ln708_311_fu_320_p1 );

    SC_METHOD(thread_trunc_ln708_312_fu_388_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_trunc_ln708_313_fu_614_p4);
    sensitive << ( ap_port_reg_data_6_V_read );

    SC_METHOD(thread_trunc_ln708_s_fu_130_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, trunc_ln708_s_reg_948, "trunc_ln708_s_reg_948");
    sc_trace(mVcdFile, mult_19_V_reg_953, "mult_19_V_reg_953");
    sc_trace(mVcdFile, mult_27_V_reg_958, "mult_27_V_reg_958");
    sc_trace(mVcdFile, mult_33_V_fu_220_p4, "mult_33_V_fu_220_p4");
    sc_trace(mVcdFile, mult_33_V_reg_964, "mult_33_V_reg_964");
    sc_trace(mVcdFile, trunc_ln_reg_969, "trunc_ln_reg_969");
    sc_trace(mVcdFile, trunc_ln708_132_fu_352_p4, "trunc_ln708_132_fu_352_p4");
    sc_trace(mVcdFile, trunc_ln708_132_reg_974, "trunc_ln708_132_reg_974");
    sc_trace(mVcdFile, trunc_ln708_133_reg_979, "trunc_ln708_133_reg_979");
    sc_trace(mVcdFile, trunc_ln708_312_reg_984, "trunc_ln708_312_reg_984");
    sc_trace(mVcdFile, trunc_ln708_136_fu_416_p4, "trunc_ln708_136_fu_416_p4");
    sc_trace(mVcdFile, trunc_ln708_136_reg_989, "trunc_ln708_136_reg_989");
    sc_trace(mVcdFile, trunc_ln708_140_reg_995, "trunc_ln708_140_reg_995");
    sc_trace(mVcdFile, trunc_ln708_141_reg_1001, "trunc_ln708_141_reg_1001");
    sc_trace(mVcdFile, trunc_ln708_142_fu_470_p4, "trunc_ln708_142_fu_470_p4");
    sc_trace(mVcdFile, trunc_ln708_142_reg_1006, "trunc_ln708_142_reg_1006");
    sc_trace(mVcdFile, acc_13_V_reg_1011, "acc_13_V_reg_1011");
    sc_trace(mVcdFile, trunc_ln708_144_reg_1018, "trunc_ln708_144_reg_1018");
    sc_trace(mVcdFile, trunc_ln708_145_fu_524_p4, "trunc_ln708_145_fu_524_p4");
    sc_trace(mVcdFile, trunc_ln708_145_reg_1023, "trunc_ln708_145_reg_1023");
    sc_trace(mVcdFile, add_ln703_386_fu_534_p2, "add_ln703_386_fu_534_p2");
    sc_trace(mVcdFile, add_ln703_386_reg_1029, "add_ln703_386_reg_1029");
    sc_trace(mVcdFile, add_ln703_389_fu_540_p2, "add_ln703_389_fu_540_p2");
    sc_trace(mVcdFile, add_ln703_389_reg_1034, "add_ln703_389_reg_1034");
    sc_trace(mVcdFile, add_ln703_390_fu_546_p2, "add_ln703_390_fu_546_p2");
    sc_trace(mVcdFile, add_ln703_390_reg_1039, "add_ln703_390_reg_1039");
    sc_trace(mVcdFile, add_ln703_394_fu_552_p2, "add_ln703_394_fu_552_p2");
    sc_trace(mVcdFile, add_ln703_394_reg_1044, "add_ln703_394_reg_1044");
    sc_trace(mVcdFile, add_ln703_402_fu_558_p2, "add_ln703_402_fu_558_p2");
    sc_trace(mVcdFile, add_ln703_402_reg_1049, "add_ln703_402_reg_1049");
    sc_trace(mVcdFile, add_ln703_405_fu_564_p2, "add_ln703_405_fu_564_p2");
    sc_trace(mVcdFile, add_ln703_405_reg_1054, "add_ln703_405_reg_1054");
    sc_trace(mVcdFile, tmp_32_reg_1059, "tmp_32_reg_1059");
    sc_trace(mVcdFile, ap_port_reg_data_6_V_read, "ap_port_reg_data_6_V_read");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sext_ln1116_cast22_fu_126_p0, "sext_ln1116_cast22_fu_126_p0");
    sc_trace(mVcdFile, trunc_ln708_s_fu_130_p1, "trunc_ln708_s_fu_130_p1");
    sc_trace(mVcdFile, shl_ln_fu_140_p1, "shl_ln_fu_140_p1");
    sc_trace(mVcdFile, shl_ln_fu_140_p3, "shl_ln_fu_140_p3");
    sc_trace(mVcdFile, sext_ln1116_cast22_fu_126_p1, "sext_ln1116_cast22_fu_126_p1");
    sc_trace(mVcdFile, sub_ln1118_fu_148_p2, "sub_ln1118_fu_148_p2");
    sc_trace(mVcdFile, shl_ln1118_s_fu_174_p3, "shl_ln1118_s_fu_174_p3");
    sc_trace(mVcdFile, sub_ln1118_184_fu_182_p2, "sub_ln1118_184_fu_182_p2");
    sc_trace(mVcdFile, sext_ln1116_253_cast_fu_198_p0, "sext_ln1116_253_cast_fu_198_p0");
    sc_trace(mVcdFile, shl_ln1118_173_fu_202_p1, "shl_ln1118_173_fu_202_p1");
    sc_trace(mVcdFile, shl_ln1118_173_fu_202_p3, "shl_ln1118_173_fu_202_p3");
    sc_trace(mVcdFile, sext_ln1118_fu_210_p1, "sext_ln1118_fu_210_p1");
    sc_trace(mVcdFile, sub_ln1118_185_fu_214_p2, "sub_ln1118_185_fu_214_p2");
    sc_trace(mVcdFile, mult_36_V_fu_230_p1, "mult_36_V_fu_230_p1");
    sc_trace(mVcdFile, shl_ln1118_174_fu_240_p1, "shl_ln1118_174_fu_240_p1");
    sc_trace(mVcdFile, shl_ln1118_174_fu_240_p3, "shl_ln1118_174_fu_240_p3");
    sc_trace(mVcdFile, sext_ln1116_253_cast_fu_198_p1, "sext_ln1116_253_cast_fu_198_p1");
    sc_trace(mVcdFile, sext_ln1116_254_cast_fu_254_p0, "sext_ln1116_254_cast_fu_254_p0");
    sc_trace(mVcdFile, shl_ln1118_175_fu_258_p1, "shl_ln1118_175_fu_258_p1");
    sc_trace(mVcdFile, shl_ln1118_175_fu_258_p3, "shl_ln1118_175_fu_258_p3");
    sc_trace(mVcdFile, sext_ln1116_254_cast_fu_254_p1, "sext_ln1116_254_cast_fu_254_p1");
    sc_trace(mVcdFile, sub_ln1118_187_fu_266_p2, "sub_ln1118_187_fu_266_p2");
    sc_trace(mVcdFile, sub_ln1118_210_fu_282_p2, "sub_ln1118_210_fu_282_p2");
    sc_trace(mVcdFile, sub_ln1118_188_fu_298_p2, "sub_ln1118_188_fu_298_p2");
    sc_trace(mVcdFile, sub_ln1118_189_fu_304_p2, "sub_ln1118_189_fu_304_p2");
    sc_trace(mVcdFile, trunc_ln708_311_fu_320_p1, "trunc_ln708_311_fu_320_p1");
    sc_trace(mVcdFile, trunc_ln708_311_fu_320_p4, "trunc_ln708_311_fu_320_p4");
    sc_trace(mVcdFile, sext_ln1116_255_cast_fu_334_p0, "sext_ln1116_255_cast_fu_334_p0");
    sc_trace(mVcdFile, p_shl5_fu_338_p1, "p_shl5_fu_338_p1");
    sc_trace(mVcdFile, sext_ln1116_255_cast_fu_334_p1, "sext_ln1116_255_cast_fu_334_p1");
    sc_trace(mVcdFile, p_shl5_fu_338_p3, "p_shl5_fu_338_p3");
    sc_trace(mVcdFile, sub_ln1118_211_fu_346_p2, "sub_ln1118_211_fu_346_p2");
    sc_trace(mVcdFile, sub_ln1118_190_fu_362_p2, "sub_ln1118_190_fu_362_p2");
    sc_trace(mVcdFile, trunc_ln708_134_fu_378_p1, "trunc_ln708_134_fu_378_p1");
    sc_trace(mVcdFile, trunc_ln708_312_fu_388_p1, "trunc_ln708_312_fu_388_p1");
    sc_trace(mVcdFile, sext_ln1116_256_cast_fu_398_p0, "sext_ln1116_256_cast_fu_398_p0");
    sc_trace(mVcdFile, p_shl3_fu_402_p1, "p_shl3_fu_402_p1");
    sc_trace(mVcdFile, sext_ln1116_256_cast_fu_398_p1, "sext_ln1116_256_cast_fu_398_p1");
    sc_trace(mVcdFile, p_shl3_fu_402_p3, "p_shl3_fu_402_p3");
    sc_trace(mVcdFile, sub_ln1118_212_fu_410_p2, "sub_ln1118_212_fu_410_p2");
    sc_trace(mVcdFile, sext_ln1116_258_cast_fu_426_p0, "sext_ln1116_258_cast_fu_426_p0");
    sc_trace(mVcdFile, shl_ln1118_177_fu_430_p1, "shl_ln1118_177_fu_430_p1");
    sc_trace(mVcdFile, shl_ln1118_177_fu_430_p3, "shl_ln1118_177_fu_430_p3");
    sc_trace(mVcdFile, sext_ln1116_258_cast_fu_426_p1, "sext_ln1116_258_cast_fu_426_p1");
    sc_trace(mVcdFile, sub_ln1118_192_fu_438_p2, "sub_ln1118_192_fu_438_p2");
    sc_trace(mVcdFile, sub_ln1118_213_fu_454_p2, "sub_ln1118_213_fu_454_p2");
    sc_trace(mVcdFile, trunc_ln708_142_fu_470_p1, "trunc_ln708_142_fu_470_p1");
    sc_trace(mVcdFile, sext_ln1116_259_cast_fu_480_p0, "sext_ln1116_259_cast_fu_480_p0");
    sc_trace(mVcdFile, shl_ln1118_178_fu_484_p1, "shl_ln1118_178_fu_484_p1");
    sc_trace(mVcdFile, shl_ln1118_178_fu_484_p3, "shl_ln1118_178_fu_484_p3");
    sc_trace(mVcdFile, sext_ln1116_259_cast_fu_480_p1, "sext_ln1116_259_cast_fu_480_p1");
    sc_trace(mVcdFile, sub_ln1118_193_fu_492_p2, "sub_ln1118_193_fu_492_p2");
    sc_trace(mVcdFile, sub_ln1118_214_fu_508_p2, "sub_ln1118_214_fu_508_p2");
    sc_trace(mVcdFile, trunc_ln708_145_fu_524_p1, "trunc_ln708_145_fu_524_p1");
    sc_trace(mVcdFile, mult_52_V_fu_272_p4, "mult_52_V_fu_272_p4");
    sc_trace(mVcdFile, mult_36_V_fu_230_p4, "mult_36_V_fu_230_p4");
    sc_trace(mVcdFile, mult_53_V_fu_288_p4, "mult_53_V_fu_288_p4");
    sc_trace(mVcdFile, trunc_ln708_134_fu_378_p4, "trunc_ln708_134_fu_378_p4");
    sc_trace(mVcdFile, sext_ln708_fu_330_p1, "sext_ln708_fu_330_p1");
    sc_trace(mVcdFile, mult_15_V_fu_154_p4, "mult_15_V_fu_154_p4");
    sc_trace(mVcdFile, sub_ln1118_186_fu_248_p2, "sub_ln1118_186_fu_248_p2");
    sc_trace(mVcdFile, shl_ln1118_176_fu_596_p3, "shl_ln1118_176_fu_596_p3");
    sc_trace(mVcdFile, sext_ln1118_326_fu_604_p1, "sext_ln1118_326_fu_604_p1");
    sc_trace(mVcdFile, trunc_ln708_313_fu_614_p4, "trunc_ln708_313_fu_614_p4");
    sc_trace(mVcdFile, trunc_ln708_137_fu_586_p4, "trunc_ln708_137_fu_586_p4");
    sc_trace(mVcdFile, add_ln703_382_fu_632_p2, "add_ln703_382_fu_632_p2");
    sc_trace(mVcdFile, add_ln703_384_fu_642_p2, "add_ln703_384_fu_642_p2");
    sc_trace(mVcdFile, add_ln703_387_fu_652_p2, "add_ln703_387_fu_652_p2");
    sc_trace(mVcdFile, add_ln703_391_fu_662_p2, "add_ln703_391_fu_662_p2");
    sc_trace(mVcdFile, add_ln703_395_fu_676_p2, "add_ln703_395_fu_676_p2");
    sc_trace(mVcdFile, add_ln703_397_fu_685_p2, "add_ln703_397_fu_685_p2");
    sc_trace(mVcdFile, add_ln703_399_fu_695_p2, "add_ln703_399_fu_695_p2");
    sc_trace(mVcdFile, mult_14_V_fu_580_p1, "mult_14_V_fu_580_p1");
    sc_trace(mVcdFile, add_ln703_403_fu_709_p2, "add_ln703_403_fu_709_p2");
    sc_trace(mVcdFile, sext_ln708_80_fu_624_p1, "sext_ln708_80_fu_624_p1");
    sc_trace(mVcdFile, sext_ln708_79_fu_583_p1, "sext_ln708_79_fu_583_p1");
    sc_trace(mVcdFile, add_ln703_406_fu_719_p2, "add_ln703_406_fu_719_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_628_p2, "p_Val2_s_fu_628_p2");
    sc_trace(mVcdFile, acc_1_V_fu_637_p2, "acc_1_V_fu_637_p2");
    sc_trace(mVcdFile, acc_3_V_fu_647_p2, "acc_3_V_fu_647_p2");
    sc_trace(mVcdFile, acc_4_V_fu_657_p2, "acc_4_V_fu_657_p2");
    sc_trace(mVcdFile, acc_5_V_fu_666_p2, "acc_5_V_fu_666_p2");
    sc_trace(mVcdFile, sub_ln1118_191_fu_608_p2, "sub_ln1118_191_fu_608_p2");
    sc_trace(mVcdFile, tmp_fu_770_p4, "tmp_fu_770_p4");
    sc_trace(mVcdFile, acc_7_V_fu_671_p2, "acc_7_V_fu_671_p2");
    sc_trace(mVcdFile, acc_8_V_fu_680_p2, "acc_8_V_fu_680_p2");
    sc_trace(mVcdFile, acc_9_V_fu_690_p2, "acc_9_V_fu_690_p2");
    sc_trace(mVcdFile, acc_10_V_fu_699_p2, "acc_10_V_fu_699_p2");
    sc_trace(mVcdFile, acc_11_V_fu_704_p2, "acc_11_V_fu_704_p2");
    sc_trace(mVcdFile, acc_14_V_fu_714_p2, "acc_14_V_fu_714_p2");
    sc_trace(mVcdFile, acc_15_V_fu_725_p2, "acc_15_V_fu_725_p2");
    sc_trace(mVcdFile, res_0_V_write_assign_fu_730_p3, "res_0_V_write_assign_fu_730_p3");
    sc_trace(mVcdFile, res_1_V_write_assign_fu_738_p3, "res_1_V_write_assign_fu_738_p3");
    sc_trace(mVcdFile, res_3_V_write_assign_fu_746_p3, "res_3_V_write_assign_fu_746_p3");
    sc_trace(mVcdFile, res_4_V_write_assign_fu_754_p3, "res_4_V_write_assign_fu_754_p3");
    sc_trace(mVcdFile, res_5_V_write_assign_fu_762_p3, "res_5_V_write_assign_fu_762_p3");
    sc_trace(mVcdFile, res_6_V_write_assign_fu_780_p3, "res_6_V_write_assign_fu_780_p3");
    sc_trace(mVcdFile, res_7_V_write_assign_fu_788_p3, "res_7_V_write_assign_fu_788_p3");
    sc_trace(mVcdFile, res_8_V_write_assign_fu_796_p3, "res_8_V_write_assign_fu_796_p3");
    sc_trace(mVcdFile, res_9_V_write_assign_fu_804_p3, "res_9_V_write_assign_fu_804_p3");
    sc_trace(mVcdFile, res_10_V_write_assign_fu_812_p3, "res_10_V_write_assign_fu_812_p3");
    sc_trace(mVcdFile, res_11_V_write_assign_fu_820_p3, "res_11_V_write_assign_fu_820_p3");
    sc_trace(mVcdFile, res_12_V_write_assign_fu_828_p3, "res_12_V_write_assign_fu_828_p3");
    sc_trace(mVcdFile, res_13_V_write_assign_fu_835_p3, "res_13_V_write_assign_fu_835_p3");
    sc_trace(mVcdFile, res_14_V_write_assign_fu_842_p3, "res_14_V_write_assign_fu_842_p3");
    sc_trace(mVcdFile, res_15_V_write_assign_fu_850_p3, "res_15_V_write_assign_fu_850_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::~dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        acc_13_V_reg_1011 = sub_ln1118_193_fu_492_p2.read().range(17, 8);
        add_ln703_386_reg_1029 = add_ln703_386_fu_534_p2.read();
        add_ln703_389_reg_1034 = add_ln703_389_fu_540_p2.read();
        add_ln703_390_reg_1039 = add_ln703_390_fu_546_p2.read();
        add_ln703_394_reg_1044 = add_ln703_394_fu_552_p2.read();
        add_ln703_402_reg_1049 = add_ln703_402_fu_558_p2.read();
        add_ln703_405_reg_1054 = add_ln703_405_fu_564_p2.read();
        ap_port_reg_data_6_V_read = data_6_V_read.read();
        mult_19_V_reg_953 = data_1_V_read.read().range(15, 6);
        mult_27_V_reg_958 = sub_ln1118_184_fu_182_p2.read().range(17, 8);
        mult_33_V_reg_964 = sub_ln1118_185_fu_214_p2.read().range(17, 8);
        tmp_32_reg_1059 = sub_ln1118_186_fu_248_p2.read().range(17, 8);
        trunc_ln708_132_reg_974 = sub_ln1118_211_fu_346_p2.read().range(17, 8);
        trunc_ln708_133_reg_979 = sub_ln1118_190_fu_362_p2.read().range(17, 8);
        trunc_ln708_136_reg_989 = sub_ln1118_212_fu_410_p2.read().range(17, 8);
        trunc_ln708_140_reg_995 = sub_ln1118_192_fu_438_p2.read().range(17, 8);
        trunc_ln708_141_reg_1001 = sub_ln1118_213_fu_454_p2.read().range(17, 8);
        trunc_ln708_142_reg_1006 = trunc_ln708_142_fu_470_p1.read().range(15, 6);
        trunc_ln708_144_reg_1018 = sub_ln1118_214_fu_508_p2.read().range(17, 8);
        trunc_ln708_145_reg_1023 = trunc_ln708_145_fu_524_p1.read().range(15, 6);
        trunc_ln708_312_reg_984 = trunc_ln708_312_fu_388_p1.read().range(15, 7);
        trunc_ln708_s_reg_948 = trunc_ln708_s_fu_130_p1.read().range(15, 7);
        trunc_ln_reg_969 = sub_ln1118_189_fu_304_p2.read().range(17, 8);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_10_V_fu_699_p2() {
    acc_10_V_fu_699_p2 = (!trunc_ln_reg_969.read().is_01() || !add_ln703_399_fu_695_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln_reg_969.read()) + sc_biguint<10>(add_ln703_399_fu_695_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_11_V_fu_704_p2() {
    acc_11_V_fu_704_p2 = (!mult_27_V_reg_958.read().is_01() || !ap_const_lv10_2.is_01())? sc_lv<10>(): (sc_biguint<10>(mult_27_V_reg_958.read()) + sc_biguint<10>(ap_const_lv10_2));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_14_V_fu_714_p2() {
    acc_14_V_fu_714_p2 = (!add_ln703_402_reg_1049.read().is_01() || !add_ln703_403_fu_709_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln703_402_reg_1049.read()) + sc_biguint<10>(add_ln703_403_fu_709_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_15_V_fu_725_p2() {
    acc_15_V_fu_725_p2 = (!add_ln703_405_reg_1054.read().is_01() || !add_ln703_406_fu_719_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln703_405_reg_1054.read()) + sc_biguint<10>(add_ln703_406_fu_719_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_1_V_fu_637_p2() {
    acc_1_V_fu_637_p2 = (!mult_33_V_reg_964.read().is_01() || !add_ln703_382_fu_632_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(mult_33_V_reg_964.read()) + sc_biguint<10>(add_ln703_382_fu_632_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_3_V_fu_647_p2() {
    acc_3_V_fu_647_p2 = (!mult_19_V_reg_953.read().is_01() || !add_ln703_384_fu_642_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(mult_19_V_reg_953.read()) + sc_biguint<10>(add_ln703_384_fu_642_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_4_V_fu_657_p2() {
    acc_4_V_fu_657_p2 = (!add_ln703_386_reg_1029.read().is_01() || !add_ln703_387_fu_652_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln703_386_reg_1029.read()) + sc_biguint<10>(add_ln703_387_fu_652_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_5_V_fu_666_p2() {
    acc_5_V_fu_666_p2 = (!add_ln703_389_reg_1034.read().is_01() || !add_ln703_391_fu_662_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln703_389_reg_1034.read()) + sc_biguint<10>(add_ln703_391_fu_662_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_7_V_fu_671_p2() {
    acc_7_V_fu_671_p2 = (!trunc_ln708_133_reg_979.read().is_01() || !ap_const_lv10_3FF.is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_133_reg_979.read()) + sc_bigint<10>(ap_const_lv10_3FF));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_8_V_fu_680_p2() {
    acc_8_V_fu_680_p2 = (!add_ln703_394_reg_1044.read().is_01() || !add_ln703_395_fu_676_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln703_394_reg_1044.read()) + sc_biguint<10>(add_ln703_395_fu_676_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_acc_9_V_fu_690_p2() {
    acc_9_V_fu_690_p2 = (!trunc_ln708_136_reg_989.read().is_01() || !add_ln703_397_fu_685_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_136_reg_989.read()) + sc_biguint<10>(add_ln703_397_fu_685_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_382_fu_632_p2() {
    add_ln703_382_fu_632_p2 = (!trunc_ln708_137_fu_586_p4.read().is_01() || !trunc_ln708_132_reg_974.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_137_fu_586_p4.read()) + sc_biguint<10>(trunc_ln708_132_reg_974.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_384_fu_642_p2() {
    add_ln703_384_fu_642_p2 = (!trunc_ln708_144_reg_1018.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_144_reg_1018.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_386_fu_534_p2() {
    add_ln703_386_fu_534_p2 = (!mult_52_V_fu_272_p4.read().is_01() || !mult_36_V_fu_230_p4.read().is_01())? sc_lv<10>(): (sc_biguint<10>(mult_52_V_fu_272_p4.read()) + sc_biguint<10>(mult_36_V_fu_230_p4.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_387_fu_652_p2() {
    add_ln703_387_fu_652_p2 = (!trunc_ln708_141_reg_1001.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_141_reg_1001.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_389_fu_540_p2() {
    add_ln703_389_fu_540_p2 = (!trunc_ln708_132_fu_352_p4.read().is_01() || !mult_53_V_fu_288_p4.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_132_fu_352_p4.read()) + sc_biguint<10>(mult_53_V_fu_288_p4.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_390_fu_546_p2() {
    add_ln703_390_fu_546_p2 = (!trunc_ln708_142_fu_470_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_142_fu_470_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_391_fu_662_p2() {
    add_ln703_391_fu_662_p2 = (!trunc_ln708_136_reg_989.read().is_01() || !add_ln703_390_reg_1039.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_136_reg_989.read()) + sc_biguint<10>(add_ln703_390_reg_1039.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_394_fu_552_p2() {
    add_ln703_394_fu_552_p2 = (!trunc_ln708_136_fu_416_p4.read().is_01() || !mult_33_V_fu_220_p4.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_136_fu_416_p4.read()) + sc_biguint<10>(mult_33_V_fu_220_p4.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_395_fu_676_p2() {
    add_ln703_395_fu_676_p2 = (!trunc_ln708_145_reg_1023.read().is_01() || !trunc_ln708_142_reg_1006.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_145_reg_1023.read()) + sc_biguint<10>(trunc_ln708_142_reg_1006.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_397_fu_685_p2() {
    add_ln703_397_fu_685_p2 = (!acc_13_V_reg_1011.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(acc_13_V_reg_1011.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_399_fu_695_p2() {
    add_ln703_399_fu_695_p2 = (!trunc_ln708_145_reg_1023.read().is_01() || !trunc_ln708_140_reg_995.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_145_reg_1023.read()) + sc_biguint<10>(trunc_ln708_140_reg_995.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_402_fu_558_p2() {
    add_ln703_402_fu_558_p2 = (!trunc_ln708_145_fu_524_p4.read().is_01() || !trunc_ln708_134_fu_378_p4.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln708_145_fu_524_p4.read()) + sc_biguint<10>(trunc_ln708_134_fu_378_p4.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_403_fu_709_p2() {
    add_ln703_403_fu_709_p2 = (!mult_14_V_fu_580_p1.read().is_01() || !mult_27_V_reg_958.read().is_01())? sc_lv<10>(): (sc_bigint<10>(mult_14_V_fu_580_p1.read()) + sc_biguint<10>(mult_27_V_reg_958.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_405_fu_564_p2() {
    add_ln703_405_fu_564_p2 = (!sext_ln708_fu_330_p1.read().is_01() || !mult_15_V_fu_154_p4.read().is_01())? sc_lv<10>(): (sc_bigint<10>(sext_ln708_fu_330_p1.read()) + sc_biguint<10>(mult_15_V_fu_154_p4.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_add_ln703_406_fu_719_p2() {
    add_ln703_406_fu_719_p2 = (!sext_ln708_80_fu_624_p1.read().is_01() || !sext_ln708_79_fu_583_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(sext_ln708_80_fu_624_p1.read()) + sc_bigint<10>(sext_ln708_79_fu_583_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_0() {
    ap_return_0 = res_0_V_write_assign_fu_730_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_1() {
    ap_return_1 = res_1_V_write_assign_fu_738_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_10() {
    ap_return_10 = res_11_V_write_assign_fu_820_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_11() {
    ap_return_11 = res_12_V_write_assign_fu_828_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_12() {
    ap_return_12 = res_13_V_write_assign_fu_835_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_13() {
    ap_return_13 = res_14_V_write_assign_fu_842_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_14() {
    ap_return_14 = res_15_V_write_assign_fu_850_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_2() {
    ap_return_2 = res_3_V_write_assign_fu_746_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_3() {
    ap_return_3 = res_4_V_write_assign_fu_754_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_4() {
    ap_return_4 = res_5_V_write_assign_fu_762_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_5() {
    ap_return_5 = res_6_V_write_assign_fu_780_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_6() {
    ap_return_6 = res_7_V_write_assign_fu_788_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_7() {
    ap_return_7 = res_8_V_write_assign_fu_796_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_8() {
    ap_return_8 = res_9_V_write_assign_fu_804_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_return_9() {
    ap_return_9 = res_10_V_write_assign_fu_812_p3.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_mult_14_V_fu_580_p1() {
    mult_14_V_fu_580_p1 = esl_sext<10,9>(trunc_ln708_s_reg_948.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_mult_15_V_fu_154_p4() {
    mult_15_V_fu_154_p4 = sub_ln1118_fu_148_p2.read().range(17, 8);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_mult_33_V_fu_220_p4() {
    mult_33_V_fu_220_p4 = sub_ln1118_185_fu_214_p2.read().range(17, 8);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_mult_36_V_fu_230_p1() {
    mult_36_V_fu_230_p1 = data_2_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_mult_36_V_fu_230_p4() {
    mult_36_V_fu_230_p4 = mult_36_V_fu_230_p1.read().range(15, 6);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_mult_52_V_fu_272_p4() {
    mult_52_V_fu_272_p4 = sub_ln1118_187_fu_266_p2.read().range(17, 8);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_mult_53_V_fu_288_p4() {
    mult_53_V_fu_288_p4 = sub_ln1118_210_fu_282_p2.read().range(17, 8);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_p_Val2_s_fu_628_p2() {
    p_Val2_s_fu_628_p2 = (!acc_13_V_reg_1011.read().is_01() || !trunc_ln708_140_reg_995.read().is_01())? sc_lv<10>(): (sc_biguint<10>(acc_13_V_reg_1011.read()) + sc_biguint<10>(trunc_ln708_140_reg_995.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_p_shl3_fu_402_p1() {
    p_shl3_fu_402_p1 = data_5_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_p_shl3_fu_402_p3() {
    p_shl3_fu_402_p3 = esl_concat<16,2>(p_shl3_fu_402_p1.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_p_shl5_fu_338_p1() {
    p_shl5_fu_338_p1 = data_4_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_p_shl5_fu_338_p3() {
    p_shl5_fu_338_p3 = esl_concat<16,2>(p_shl5_fu_338_p1.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_0_V_write_assign_fu_730_p3() {
    res_0_V_write_assign_fu_730_p3 = esl_concat<10,6>(p_Val2_s_fu_628_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_10_V_write_assign_fu_812_p3() {
    res_10_V_write_assign_fu_812_p3 = esl_concat<10,6>(acc_10_V_fu_699_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_11_V_write_assign_fu_820_p3() {
    res_11_V_write_assign_fu_820_p3 = esl_concat<10,6>(acc_11_V_fu_704_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_12_V_write_assign_fu_828_p3() {
    res_12_V_write_assign_fu_828_p3 = esl_concat<10,6>(tmp_32_reg_1059.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_13_V_write_assign_fu_835_p3() {
    res_13_V_write_assign_fu_835_p3 = esl_concat<10,6>(acc_13_V_reg_1011.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_14_V_write_assign_fu_842_p3() {
    res_14_V_write_assign_fu_842_p3 = esl_concat<10,6>(acc_14_V_fu_714_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_15_V_write_assign_fu_850_p3() {
    res_15_V_write_assign_fu_850_p3 = esl_concat<10,6>(acc_15_V_fu_725_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_1_V_write_assign_fu_738_p3() {
    res_1_V_write_assign_fu_738_p3 = esl_concat<10,6>(acc_1_V_fu_637_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_3_V_write_assign_fu_746_p3() {
    res_3_V_write_assign_fu_746_p3 = esl_concat<10,6>(acc_3_V_fu_647_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_4_V_write_assign_fu_754_p3() {
    res_4_V_write_assign_fu_754_p3 = esl_concat<10,6>(acc_4_V_fu_657_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_5_V_write_assign_fu_762_p3() {
    res_5_V_write_assign_fu_762_p3 = esl_concat<10,6>(acc_5_V_fu_666_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_6_V_write_assign_fu_780_p3() {
    res_6_V_write_assign_fu_780_p3 = esl_concat<10,6>(tmp_fu_770_p4.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_7_V_write_assign_fu_788_p3() {
    res_7_V_write_assign_fu_788_p3 = esl_concat<10,6>(acc_7_V_fu_671_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_8_V_write_assign_fu_796_p3() {
    res_8_V_write_assign_fu_796_p3 = esl_concat<10,6>(acc_8_V_fu_680_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_res_9_V_write_assign_fu_804_p3() {
    res_9_V_write_assign_fu_804_p3 = esl_concat<10,6>(acc_9_V_fu_690_p2.read(), ap_const_lv6_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_253_cast_fu_198_p0() {
    sext_ln1116_253_cast_fu_198_p0 = data_2_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_253_cast_fu_198_p1() {
    sext_ln1116_253_cast_fu_198_p1 = esl_sext<18,16>(sext_ln1116_253_cast_fu_198_p0.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_254_cast_fu_254_p0() {
    sext_ln1116_254_cast_fu_254_p0 = data_3_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_254_cast_fu_254_p1() {
    sext_ln1116_254_cast_fu_254_p1 = esl_sext<18,16>(sext_ln1116_254_cast_fu_254_p0.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_255_cast_fu_334_p0() {
    sext_ln1116_255_cast_fu_334_p0 = data_4_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_255_cast_fu_334_p1() {
    sext_ln1116_255_cast_fu_334_p1 = esl_sext<18,16>(sext_ln1116_255_cast_fu_334_p0.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_256_cast_fu_398_p0() {
    sext_ln1116_256_cast_fu_398_p0 = data_5_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_256_cast_fu_398_p1() {
    sext_ln1116_256_cast_fu_398_p1 = esl_sext<18,16>(sext_ln1116_256_cast_fu_398_p0.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_258_cast_fu_426_p0() {
    sext_ln1116_258_cast_fu_426_p0 = data_7_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_258_cast_fu_426_p1() {
    sext_ln1116_258_cast_fu_426_p1 = esl_sext<18,16>(sext_ln1116_258_cast_fu_426_p0.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_259_cast_fu_480_p0() {
    sext_ln1116_259_cast_fu_480_p0 = data_8_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_259_cast_fu_480_p1() {
    sext_ln1116_259_cast_fu_480_p1 = esl_sext<18,16>(sext_ln1116_259_cast_fu_480_p0.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_cast22_fu_126_p0() {
    sext_ln1116_cast22_fu_126_p0 = data_0_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1116_cast22_fu_126_p1() {
    sext_ln1116_cast22_fu_126_p1 = esl_sext<18,16>(sext_ln1116_cast22_fu_126_p0.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_326_fu_604_p1() {
    sext_ln1118_326_fu_604_p1 = esl_sext<18,17>(shl_ln1118_176_fu_596_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_fu_210_p1() {
    sext_ln1118_fu_210_p1 = esl_sext<18,17>(shl_ln1118_173_fu_202_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln708_79_fu_583_p1() {
    sext_ln708_79_fu_583_p1 = esl_sext<10,9>(trunc_ln708_312_reg_984.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln708_80_fu_624_p1() {
    sext_ln708_80_fu_624_p1 = esl_sext<10,9>(trunc_ln708_313_fu_614_p4.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sext_ln708_fu_330_p1() {
    sext_ln708_fu_330_p1 = esl_sext<10,9>(trunc_ln708_311_fu_320_p4.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_173_fu_202_p1() {
    shl_ln1118_173_fu_202_p1 = data_2_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_173_fu_202_p3() {
    shl_ln1118_173_fu_202_p3 = esl_concat<16,1>(shl_ln1118_173_fu_202_p1.read(), ap_const_lv1_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_174_fu_240_p1() {
    shl_ln1118_174_fu_240_p1 = data_2_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_174_fu_240_p3() {
    shl_ln1118_174_fu_240_p3 = esl_concat<16,2>(shl_ln1118_174_fu_240_p1.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_175_fu_258_p1() {
    shl_ln1118_175_fu_258_p1 = data_3_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_175_fu_258_p3() {
    shl_ln1118_175_fu_258_p3 = esl_concat<16,2>(shl_ln1118_175_fu_258_p1.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_176_fu_596_p3() {
    shl_ln1118_176_fu_596_p3 = esl_concat<16,1>(ap_port_reg_data_6_V_read.read(), ap_const_lv1_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_177_fu_430_p1() {
    shl_ln1118_177_fu_430_p1 = data_7_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_177_fu_430_p3() {
    shl_ln1118_177_fu_430_p3 = esl_concat<16,2>(shl_ln1118_177_fu_430_p1.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_178_fu_484_p1() {
    shl_ln1118_178_fu_484_p1 = data_8_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_178_fu_484_p3() {
    shl_ln1118_178_fu_484_p3 = esl_concat<16,2>(shl_ln1118_178_fu_484_p1.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_s_fu_174_p3() {
    shl_ln1118_s_fu_174_p3 = esl_concat<16,2>(data_1_V_read.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln_fu_140_p1() {
    shl_ln_fu_140_p1 = data_0_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_shl_ln_fu_140_p3() {
    shl_ln_fu_140_p3 = esl_concat<16,2>(shl_ln_fu_140_p1.read(), ap_const_lv2_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_184_fu_182_p2() {
    sub_ln1118_184_fu_182_p2 = (!ap_const_lv18_0.is_01() || !shl_ln1118_s_fu_174_p3.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_biguint<18>(shl_ln1118_s_fu_174_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_185_fu_214_p2() {
    sub_ln1118_185_fu_214_p2 = (!ap_const_lv18_0.is_01() || !sext_ln1118_fu_210_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_bigint<18>(sext_ln1118_fu_210_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_186_fu_248_p2() {
    sub_ln1118_186_fu_248_p2 = (!shl_ln1118_174_fu_240_p3.read().is_01() || !sext_ln1116_253_cast_fu_198_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(shl_ln1118_174_fu_240_p3.read()) - sc_bigint<18>(sext_ln1116_253_cast_fu_198_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_187_fu_266_p2() {
    sub_ln1118_187_fu_266_p2 = (!shl_ln1118_175_fu_258_p3.read().is_01() || !sext_ln1116_254_cast_fu_254_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(shl_ln1118_175_fu_258_p3.read()) - sc_bigint<18>(sext_ln1116_254_cast_fu_254_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_188_fu_298_p2() {
    sub_ln1118_188_fu_298_p2 = (!ap_const_lv18_0.is_01() || !shl_ln1118_175_fu_258_p3.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_biguint<18>(shl_ln1118_175_fu_258_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_189_fu_304_p2() {
    sub_ln1118_189_fu_304_p2 = (!sub_ln1118_188_fu_298_p2.read().is_01() || !sext_ln1116_254_cast_fu_254_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(sub_ln1118_188_fu_298_p2.read()) - sc_bigint<18>(sext_ln1116_254_cast_fu_254_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_190_fu_362_p2() {
    sub_ln1118_190_fu_362_p2 = (!p_shl5_fu_338_p3.read().is_01() || !sext_ln1116_255_cast_fu_334_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_shl5_fu_338_p3.read()) - sc_bigint<18>(sext_ln1116_255_cast_fu_334_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_191_fu_608_p2() {
    sub_ln1118_191_fu_608_p2 = (!ap_const_lv18_0.is_01() || !sext_ln1118_326_fu_604_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_bigint<18>(sext_ln1118_326_fu_604_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_192_fu_438_p2() {
    sub_ln1118_192_fu_438_p2 = (!shl_ln1118_177_fu_430_p3.read().is_01() || !sext_ln1116_258_cast_fu_426_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(shl_ln1118_177_fu_430_p3.read()) - sc_bigint<18>(sext_ln1116_258_cast_fu_426_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_193_fu_492_p2() {
    sub_ln1118_193_fu_492_p2 = (!shl_ln1118_178_fu_484_p3.read().is_01() || !sext_ln1116_259_cast_fu_480_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(shl_ln1118_178_fu_484_p3.read()) - sc_bigint<18>(sext_ln1116_259_cast_fu_480_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_210_fu_282_p2() {
    sub_ln1118_210_fu_282_p2 = (!sext_ln1116_254_cast_fu_254_p1.read().is_01() || !shl_ln1118_175_fu_258_p3.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1116_254_cast_fu_254_p1.read()) - sc_biguint<18>(shl_ln1118_175_fu_258_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_211_fu_346_p2() {
    sub_ln1118_211_fu_346_p2 = (!sext_ln1116_255_cast_fu_334_p1.read().is_01() || !p_shl5_fu_338_p3.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1116_255_cast_fu_334_p1.read()) - sc_biguint<18>(p_shl5_fu_338_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_212_fu_410_p2() {
    sub_ln1118_212_fu_410_p2 = (!sext_ln1116_256_cast_fu_398_p1.read().is_01() || !p_shl3_fu_402_p3.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1116_256_cast_fu_398_p1.read()) - sc_biguint<18>(p_shl3_fu_402_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_213_fu_454_p2() {
    sub_ln1118_213_fu_454_p2 = (!sext_ln1116_258_cast_fu_426_p1.read().is_01() || !shl_ln1118_177_fu_430_p3.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1116_258_cast_fu_426_p1.read()) - sc_biguint<18>(shl_ln1118_177_fu_430_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_214_fu_508_p2() {
    sub_ln1118_214_fu_508_p2 = (!sext_ln1116_259_cast_fu_480_p1.read().is_01() || !shl_ln1118_178_fu_484_p3.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1116_259_cast_fu_480_p1.read()) - sc_biguint<18>(shl_ln1118_178_fu_484_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_fu_148_p2() {
    sub_ln1118_fu_148_p2 = (!shl_ln_fu_140_p3.read().is_01() || !sext_ln1116_cast22_fu_126_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(shl_ln_fu_140_p3.read()) - sc_bigint<18>(sext_ln1116_cast22_fu_126_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_tmp_fu_770_p4() {
    tmp_fu_770_p4 = sub_ln1118_191_fu_608_p2.read().range(17, 8);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_132_fu_352_p4() {
    trunc_ln708_132_fu_352_p4 = sub_ln1118_211_fu_346_p2.read().range(17, 8);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_134_fu_378_p1() {
    trunc_ln708_134_fu_378_p1 = data_4_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_134_fu_378_p4() {
    trunc_ln708_134_fu_378_p4 = trunc_ln708_134_fu_378_p1.read().range(15, 6);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_136_fu_416_p4() {
    trunc_ln708_136_fu_416_p4 = sub_ln1118_212_fu_410_p2.read().range(17, 8);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_137_fu_586_p4() {
    trunc_ln708_137_fu_586_p4 = ap_port_reg_data_6_V_read.read().range(15, 6);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_142_fu_470_p1() {
    trunc_ln708_142_fu_470_p1 = data_7_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_142_fu_470_p4() {
    trunc_ln708_142_fu_470_p4 = trunc_ln708_142_fu_470_p1.read().range(15, 6);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_145_fu_524_p1() {
    trunc_ln708_145_fu_524_p1 = data_8_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_145_fu_524_p4() {
    trunc_ln708_145_fu_524_p4 = trunc_ln708_145_fu_524_p1.read().range(15, 6);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_311_fu_320_p1() {
    trunc_ln708_311_fu_320_p1 = data_3_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_311_fu_320_p4() {
    trunc_ln708_311_fu_320_p4 = trunc_ln708_311_fu_320_p1.read().range(15, 7);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_312_fu_388_p1() {
    trunc_ln708_312_fu_388_p1 = data_4_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_313_fu_614_p4() {
    trunc_ln708_313_fu_614_p4 = ap_port_reg_data_6_V_read.read().range(15, 7);
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_trunc_ln708_s_fu_130_p1() {
    trunc_ln708_s_fu_130_p1 = data_0_V_read.read();
}

void dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

